### ISSUE TITLE
Split docker files

### ISSUE THREAD

**Issue by Stivius** [Stivius/xibo-linux#210]
**Is your feature request related to a problem? Please describe.**
I had a conversation with developers who want to build xibo linux from sources using Dockerfile. However, Dockerfile relies on *.login file which contains credentials for official snapstore.

**Describe the solution you'd like**
They should be splitted into 2 files. The second one that's actually snapping player should be based on the first one that builds the player.

**Comment by dasgarner** [comment]
Please talk with us before you make any changes to the Docker implementation - it has impact on our CI server

**Comment by Stivius** [comment]
@dasgarner, yes, I intended to do so anyway. The problem is that Dockerfile depends on your snapcraft credentials. It's not impossible to build a standalone executable without changes to Dockerfile.
